### PR TITLE
Feature/typescript finance pages

### PR DESCRIPTION
**Pull request by KristofNalesnyik**
TS Refactor of finance pages.

### CODE REVIEW

**Comment by KristofNalesnyik** [comment]
Reviewzzátok pls! :)

**Comment by DenesDanko** [comment]
Would be nice to be more consistent w/ other files:
 - type  vs.  interface
 - _id vs id
 - no separate PropType files, unless duplicate definition should be necessary
 - no ...schema naming

 //TODO: more descriptive comments, please.
 
 New line @ EOF.

Use 'if() {}' in case a parameter can be null/undefined...

**Review by DenesDanko — COMMENTED** [review]
big NO NO!

1st NO: Admin page loading generate 2 x proptypes validation error in the console.
2nd NO: delete transaction crashes the application!

**Review by DenesDanko — APPROVED** [review]
Well done, Kristof!

**Comment by KristofNalesnyik** [comment]
It says that this branch has conflicts, but I found no conflicts. Merged, closed.

**Pull request closed without merging**
